# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd8e9035e1c4ccb06efdcdad5f3139c127a7195a9ad98bee21669cabf9bd2f3f699a479105ea22424bd98e0d0c0f72cdecd411ebb954d681728d563aa31d8e6c

test:
  secret_key_base: 7ac6aba8b1124725e21e311a70554acf17114fe4b22251f542f97591beed737e7de5fc9ce3d7c579cbba8dd236fd6eb407412a8b7a0db30861bb9f50abbf942b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
